### ISSUE TITLE
Make it possible to display a download progress of the extension.

### ISSUE THREAD

**Issue by mrk21** [mrk21/firebrew#18]

**Comment by mrk21** [comment]
Occerred erros on Windows:

```
Failures:

  1) Firebrew::Downloader::normalize_uri(uri) when the uri scheme was empty should convert a file scheme
     Failure/Error: Downloader.normalize_uri(self.uri)
     URI::InvalidComponentError:
       bad component(expected absolute path component): C:/a/b.html
     # ./lib/firebrew/downloader.rb:21:in `normalize_uri'
     # ./spec/firebrew/downloader_spec.rb:10:in `block (3 levels) in <module:Firebrew>'
     # ./spec/firebrew/downloader_spec.rb:52:in `block (4 levels) in <module:Firebrew>'

  2) Firebrew::Downloader::normalize_uri(uri) when the uri scheme was empty when the path was relative should be an absolute path from the current dir
     Failure/Error: Downloader.normalize_uri(self.uri)
     URI::InvalidComponentError:
       bad component(expected absolute path component): C:/Users/admin/Documents/working/firebrew/a/b.html
     # ./lib/firebrew/downloader.rb:21:in `normalize_uri'
     # ./spec/firebrew/downloader_spec.rb:10:in `block (3 levels) in <module:Firebrew>'
     # ./spec/firebrew/downloader_spec.rb:60:in `block (5 levels) in <module:Firebrew>'

  3) Firebrew::Downloader#initialize(uri, out[, progress_options]) -> #exec() when the uri scheme was "file" should download a content which is referenced by the uri
     Failure/Error: Downloader.new(self.uri, self.out).exec
     URI::InvalidComponentError:
       bad component(expected absolute path component): C:/Users/admin/Documents/working/firebrew/spec/fixtures/firefox/extension/unpack_false.xpi
     # ./lib/firebrew/downloader.rb:21:in `normalize_uri'
     # ./lib/firebrew/downloader.rb:30:in `initialize'
     # ./spec/firebrew/downloader_spec.rb:77:in `new'
     # ./spec/firebrew/downloader_spec.rb:77:in `block (3 levels) in <module:Firebrew>'

  4) Firebrew::Downloader#initialize(uri, out[, progress_options]) -> #exec() when the uri scheme was "http" or "https" should download a content which is referenced by the uri
     Failure/Error: expect(Digest::MD5.hexdigest(self.out.read)).to eq(md5)

       expected: "dea866691da858b819c5850107b40e54"
            got: "d771d7a7ea64d9f21412ad70de7353ab"

       (compared using ==)
     # ./spec/firebrew/downloader_spec.rb:108:in `block (4 levels) in <module:Firebrew>'

  5) Firebrew::Downloader#initialize(uri, out[, progress_options]) -> #exec() when the uri scheme was "http" or "https" when the response status code was 302 should download a content which is referen
ced by the uri
     Failure/Error: expect(Digest::MD5.hexdigest(self.out.read)).to eq(md5)

       expected: "dea866691da858b819c5850107b40e54"
            got: "d771d7a7ea64d9f21412ad70de7353ab"

       (compared using ==)
     # ./spec/firebrew/downloader_spec.rb:128:in `block (5 levels) in <module:Firebrew>'

  6) Firebrew::Firefox::Extension Manager #install(extension[, is_displaying_progress]) should copy the `path/to/profile/extensions/<GUID>.xpi`
     Failure/Error: subject { self.instance.install(self.extension) }
     URI::InvalidComponentError:
       bad component(expected absolute path component): C:/Users/admin/Documents/working/firebrew/spec/fixtures/firefox/extension/unpack_false.xpi
     # ./lib/firebrew/downloader.rb:21:in `normalize_uri'
     # ./lib/firebrew/downloader.rb:30:in `initialize'
     # ./lib/firebrew/firefox/extension.rb:52:in `new'
     # ./lib/firebrew/firefox/extension.rb:52:in `block in install'
     # ./lib/firebrew/firefox/extension.rb:49:in `open'
     # ./lib/firebrew/firefox/extension.rb:49:in `install'
     # ./spec/firebrew/firefox/extension_spec.rb:92:in `block (4 levels) in <module:Firefox>'
     # ./spec/firebrew/firefox/extension_spec.rb:107:in `block (4 levels) in <module:Firefox>'

  7) Firebrew::Firefox::Extension Manager #install(extension[, is_displaying_progress]) should add the `extension` extension
     Failure/Error: subject { self.instance.install(self.extension) }
     URI::InvalidComponentError:
       bad component(expected absolute path component): C:/Users/admin/Documents/working/firebrew/spec/fixtures/firefox/extension/unpack_false.xpi
     # ./lib/firebrew/downloader.rb:21:in `normalize_uri'
     # ./lib/firebrew/downloader.rb:30:in `initialize'
     # ./lib/firebrew/firefox/extension.rb:52:in `new'
     # ./lib/firebrew/firefox/extension.rb:52:in `block in install'
     # ./lib/firebrew/firefox/extension.rb:49:in `open'
     # ./lib/firebrew/firefox/extension.rb:49:in `install'
     # ./spec/firebrew/firefox/extension_spec.rb:92:in `block (4 levels) in <module:Firefox>'
     # ./spec/firebrew/firefox/extension_spec.rb:113:in `block (4 levels) in <module:Firefox>'

  8) Firebrew::Firefox::Extension Manager #install(extension[, is_displaying_progress]) when an `uri` of the `extension` was equal or greater than two should not throw exceptions
     Failure/Error: expect{subject}.to_not raise_error
       expected no Exception, got #<URI::InvalidComponentError: bad component(expected absolute path component): C:/Users/admin/Documents/working/firebrew/spec/fixtures/firefox/extension/unpack_false.
xpi> with backtrace:
         # ./lib/firebrew/downloader.rb:21:in `normalize_uri'
         # ./lib/firebrew/downloader.rb:30:in `initialize'
         # ./lib/firebrew/firefox/extension.rb:52:in `new'
         # ./lib/firebrew/firefox/extension.rb:52:in `block in install'
         # ./lib/firebrew/firefox/extension.rb:49:in `open'
         # ./lib/firebrew/firefox/extension.rb:49:in `install'
         # ./spec/firebrew/firefox/extension_spec.rb:92:in `block (4 levels) in <module:Firefox>'
         # ./spec/firebrew/firefox/extension_spec.rb:136:in `block (6 levels) in <module:Firefox>'
         # ./spec/firebrew/firefox/extension_spec.rb:136:in `block (5 levels) in <module:Firefox>'
     # ./spec/firebrew/firefox/extension_spec.rb:136:in `block (5 levels) in <module:Firefox>'

  9) Firebrew::Firefox::Extension Manager #install(extension[, is_displaying_progress]) when an `em:unpack` value of the `install.rdf` in the XPI package not exsisted should copy the `path/to/profile/
extensions/<GUID>.xpi`
     Failure/Error: subject { self.instance.install(self.extension) }
     URI::InvalidComponentError:
       bad component(expected absolute path component): C:/Users/admin/Documents/working/firebrew/spec/fixtures/firefox/extension/unpack_null.xpi
     # ./lib/firebrew/downloader.rb:21:in `normalize_uri'
     # ./lib/firebrew/downloader.rb:30:in `initialize'
     # ./lib/firebrew/firefox/extension.rb:52:in `new'
     # ./lib/firebrew/firefox/extension.rb:52:in `block in install'
     # ./lib/firebrew/firefox/extension.rb:49:in `open'
     # ./lib/firebrew/firefox/extension.rb:49:in `install'
     # ./spec/firebrew/firefox/extension_spec.rb:92:in `block (4 levels) in <module:Firefox>'
     # ./spec/firebrew/firefox/extension_spec.rb:150:in `block (5 levels) in <module:Firefox>'

  10) Firebrew::Firefox::Extension Manager #install(extension[, is_displaying_progress]) when an `em:unpack` value of the `install.rdf` in the XPI package not exsisted should add the `extension` exten
sion
     Failure/Error: subject { self.instance.install(self.extension) }
     URI::InvalidComponentError:
       bad component(expected absolute path component): C:/Users/admin/Documents/working/firebrew/spec/fixtures/firefox/extension/unpack_null.xpi
     # ./lib/firebrew/downloader.rb:21:in `normalize_uri'
     # ./lib/firebrew/downloader.rb:30:in `initialize'
     # ./lib/firebrew/firefox/extension.rb:52:in `new'
     # ./lib/firebrew/firefox/extension.rb:52:in `block in install'
     # ./lib/firebrew/firefox/extension.rb:49:in `open'
     # ./lib/firebrew/firefox/extension.rb:49:in `install'
     # ./spec/firebrew/firefox/extension_spec.rb:92:in `block (4 levels) in <module:Firefox>'
     # ./spec/firebrew/firefox/extension_spec.rb:156:in `block (5 levels) in <module:Firefox>'

  11) Firebrew::Firefox::Extension Manager #install(extension[, is_displaying_progress]) when an `em:unpack` value of the `install.rdf` in the XPI package was true should copy the `path/to/profile/ext
ensions/<GUID>`
     Failure/Error: subject { self.instance.install(self.extension) }
     URI::InvalidComponentError:
       bad component(expected absolute path component): C:/Users/admin/Documents/working/firebrew/spec/fixtures/firefox/extension/unpack_true.xpi
     # ./lib/firebrew/downloader.rb:21:in `normalize_uri'
     # ./lib/firebrew/downloader.rb:30:in `initialize'
     # ./lib/firebrew/firefox/extension.rb:52:in `new'
     # ./lib/firebrew/firefox/extension.rb:52:in `block in install'
     # ./lib/firebrew/firefox/extension.rb:49:in `open'
     # ./lib/firebrew/firefox/extension.rb:49:in `install'
     # ./spec/firebrew/firefox/extension_spec.rb:92:in `block (4 levels) in <module:Firefox>'
     # ./spec/firebrew/firefox/extension_spec.rb:181:in `block (5 levels) in <module:Firefox>'

  12) Firebrew::Firefox::Extension Manager #install(extension[, is_displaying_progress]) when an `em:unpack` value of the `install.rdf` in the XPI package was true should unzip all files in the XPI pa
ckage
     Failure/Error: subject { self.instance.install(self.extension) }
     URI::InvalidComponentError:
       bad component(expected absolute path component): C:/Users/admin/Documents/working/firebrew/spec/fixtures/firefox/extension/unpack_true.xpi
     # ./lib/firebrew/downloader.rb:21:in `normalize_uri'
     # ./lib/firebrew/downloader.rb:30:in `initialize'
     # ./lib/firebrew/firefox/extension.rb:52:in `new'
     # ./lib/firebrew/firefox/extension.rb:52:in `block in install'
     # ./lib/firebrew/firefox/extension.rb:49:in `open'
     # ./lib/firebrew/firefox/extension.rb:49:in `install'
     # ./spec/firebrew/firefox/extension_spec.rb:92:in `block (4 levels) in <module:Firefox>'
     # ./spec/firebrew/firefox/extension_spec.rb:186:in `block (5 levels) in <module:Firefox>'

  13) Firebrew::Firefox::Extension Manager #install(extension[, is_displaying_progress]) when an `em:unpack` value of the `install.rdf` in the XPI package was true should add the `extension` extension

     Failure/Error: subject { self.instance.install(self.extension) }
     URI::InvalidComponentError:
       bad component(expected absolute path component): C:/Users/admin/Documents/working/firebrew/spec/fixtures/firefox/extension/unpack_true.xpi
     # ./lib/firebrew/downloader.rb:21:in `normalize_uri'
     # ./lib/firebrew/downloader.rb:30:in `initialize'
     # ./lib/firebrew/firefox/extension.rb:52:in `new'
     # ./lib/firebrew/firefox/extension.rb:52:in `block in install'
     # ./lib/firebrew/firefox/extension.rb:49:in `open'
     # ./lib/firebrew/firefox/extension.rb:49:in `install'
     # ./spec/firebrew/firefox/extension_spec.rb:92:in `block (4 levels) in <module:Firefox>'
     # ./spec/firebrew/firefox/extension_spec.rb:197:in `block (5 levels) in <module:Firefox>'

Failed examples:

rspec ./spec/firebrew/downloader_spec.rb:51 # Firebrew::Downloader::normalize_uri(uri) when the uri scheme was empty should convert a file scheme
rspec ./spec/firebrew/downloader_spec.rb:59 # Firebrew::Downloader::normalize_uri(uri) when the uri scheme was empty when the path was relative should be an absolute path from the current dir
rspec ./spec/firebrew/downloader_spec.rb:88 # Firebrew::Downloader#initialize(uri, out[, progress_options]) -> #exec() when the uri scheme was "file" should download a content which is referenced by t
he uri
rspec ./spec/firebrew/downloader_spec.rb:106 # Firebrew::Downloader#initialize(uri, out[, progress_options]) -> #exec() when the uri scheme was "http" or "https" should download a content which is ref
erenced by the uri
rspec ./spec/firebrew/downloader_spec.rb:126 # Firebrew::Downloader#initialize(uri, out[, progress_options]) -> #exec() when the uri scheme was "http" or "https" when the response status code was 302
should download a content which is referenced by the uri
rspec ./spec/firebrew/firefox/extension_spec.rb:106 # Firebrew::Firefox::Extension Manager #install(extension[, is_displaying_progress]) should copy the `path/to/profile/extensions/<GUID>.xpi`
rspec ./spec/firebrew/firefox/extension_spec.rb:112 # Firebrew::Firefox::Extension Manager #install(extension[, is_displaying_progress]) should add the `extension` extension
rspec ./spec/firebrew/firefox/extension_spec.rb:135 # Firebrew::Firefox::Extension Manager #install(extension[, is_displaying_progress]) when an `uri` of the `extension` was equal or greater than two
should not throw exceptions
rspec ./spec/firebrew/firefox/extension_spec.rb:149 # Firebrew::Firefox::Extension Manager #install(extension[, is_displaying_progress]) when an `em:unpack` value of the `install.rdf` in the XPI packa
ge not exsisted should copy the `path/to/profile/extensions/<GUID>.xpi`
rspec ./spec/firebrew/firefox/extension_spec.rb:155 # Firebrew::Firefox::Extension Manager #install(extension[, is_displaying_progress]) when an `em:unpack` value of the `install.rdf` in the XPI packa
ge not exsisted should add the `extension` extension
rspec ./spec/firebrew/firefox/extension_spec.rb:180 # Firebrew::Firefox::Extension Manager #install(extension[, is_displaying_progress]) when an `em:unpack` value of the `install.rdf` in the XPI packa
ge was true should copy the `path/to/profile/extensions/<GUID>`
rspec ./spec/firebrew/firefox/extension_spec.rb:185 # Firebrew::Firefox::Extension Manager #install(extension[, is_displaying_progress]) when an `em:unpack` value of the `install.rdf` in the XPI packa
ge was true should unzip all files in the XPI package
rspec ./spec/firebrew/firefox/extension_spec.rb:196 # Firebrew::Firefox::Extension Manager #install(extension[, is_displaying_progress]) when an `em:unpack` value of the `install.rdf` in the XPI packa
ge was true should add the `extension` extension
```
